name: Build and Deploy Docusaurus

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build Docusaurus
      run: npm run build

    # Upload the build directory as an artifact
    - name: Upload build directory as artifact
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: ./build

  deploy:
    runs-on: ubuntu-latest
    needs: build
  
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Download the build artifact from the build job
    - name: Download build directory
      uses: actions/download-artifact@v3
      with:
        name: build
        path: ./build
    
    - name: Deploy to GitHub Pages
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
        GIT_USER: Fan-55
        REPO: Fan-55.github.io
      run: |
        # Clone the GitHub Pages repo
        git clone https://${GH_PAT}@github.com/${GIT_USER}/${REPO}.git

        # Copy files to GitHub Pages repo
        cp -R build/. ${REPO}/

        # Configure Git
        cd ${REPO}
        git config user.name "GitHub Action"
        git config user.email "action@github.com"

        # Commit and push to the GitHub Pages repo
        git add .
        git commit -m "Deploy Docusaurus site"
        git push --force origin HEAD:gh-pages  # Use HEAD to push to the gh-pages branch
